version: "3"

services:
  flask:
    container_name: flask
    build:
      context: ./annoy-be
      target: builder
    ports:
      - 5000:5000
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=5000
    volumes:
      - ./annoy-be:/src
  
  annoy-react-ts:
    container_name: annoy-react-ts
    hostname: annoy-react-ts
    image: node:16-alpine
    ports:
      - 3000:3000
    build:
      context: ./annoy-react-ts
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./annoy-react-ts:/app
volumes:
  annoy-react-ts: